import { memo, useEffect, useRef, useState } from 'react'
import './App.css'
import './patterns.css'

type P={x:number;y:number}; type Particle=P&{ox:number;oy:number}
type PatternType='stripes'|'blocks'|'dots'|'grid'|'crosshatch'|'rings'|'waves'
type PatternRegion={id:number;x:number;y:number;w:number;h:number;type:PatternType;color:string;scale:number;opacity:number;angle:number;thickness:number;phase:number}
type VisualStyle={lineWidth:number;outlineColor:string;fillColor:string;eyeOutline:string;eyeFill:string;pupilColor:string;eyeLineWidth:number;pupilSize:number}
const INITIAL:P[]=[{x:.3,y:.29},{x:.7,y:.29},{x:.7,y:.7},{x:.3,y:.7}]
const N=64
const DEFAULT_VISUAL:VisualStyle={lineWidth:3,outlineColor:'#A7FFD5FF',fillColor:'#4A9D91E8',eyeOutline:'#D8FFF0FF',eyeFill:'#173A3EFF',pupilColor:'#071014FF',eyeLineWidth:4,pupilSize:9}
function hsvToHex(h:number,s:number,v:number){const c=v*s,hp=((h%360)+360)%360/60,x=c*(1-Math.abs(hp%2-1));let rgb=[0,0,0];if(hp<1)rgb=[c,x,0];else if(hp<2)rgb=[x,c,0];else if(hp<3)rgb=[0,c,x];else if(hp<4)rgb=[0,x,c];else if(hp<5)rgb=[x,0,c];else rgb=[c,0,x];const m=v-c;return '#'+rgb.map(n=>Math.round((n+m)*255).toString(16).padStart(2,'0')).join('').toUpperCase()}
function hexToHsv(hex:string){const n=parseInt(hex.slice(1,7),16),r=(n>>16&255)/255,g=(n>>8&255)/255,b=(n&255)/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d){if(max===r)h=60*((g-b)/d%6);else if(max===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4)}return{h:(h+360)%360,s:max?d/max:0,v:max}}
function colorAlpha(hex:string){return hex.length>=9?parseInt(hex.slice(7,9),16)/255:1}
function withAlpha(hex:string,alpha:number){return hex.slice(0,7)+Math.round(alpha*255).toString(16).padStart(2,'0').toUpperCase()}
function hexAlpha(hex:string,alpha:number){const n=parseInt(hex.slice(1,7),16);return `rgba(${n>>16&255},${n>>8&255},${n&255},${alpha*colorAlpha(hex)})`}
function hslHex(h:number,s:number,l:number,alpha=1){const a=s*Math.min(l,1-l),f=(n:number)=>{const k=(n+h/30)%12,c=l-a*Math.max(-1,Math.min(k-3,9-k,1));return Math.round(255*c).toString(16).padStart(2,'0')};return `#${f(0)}${f(8)}${f(4)}${Math.round(alpha*255).toString(16).padStart(2,'0')}`.toUpperCase()}
function layout(points:P[],w:number,h:number){
 const frame=points.map(p=>({x:p.x*w,y:p.y*h})),width=Math.hypot(frame[1].x-frame[0].x,frame[1].y-frame[0].y),height=Math.hypot(frame[2].x-frame[1].x,frame[2].y-frame[1].y)
 const horizontal=Math.max(4,Math.min(N/2-4,Math.round(N*width/(2*(width+height))))),vertical=(N-2*horizontal)/2,counts=[horizontal,vertical,horizontal,vertical]
 const anchors=[0,counts[0],counts[0]+counts[1],counts[0]+counts[1]+counts[2]]
 return{frame,counts,anchors,signature:counts.join(':')}
}
function build(points:P[],w:number,h:number):Particle[]{const {frame,counts}=layout(points,w,h),particles:Particle[]=[];counts.forEach((count,side)=>{const a=frame[side],b=frame[(side+1)%4];for(let i=0;i<count;i++){const f=i/count,x=a.x+(b.x-a.x)*f,y=a.y+(b.y-a.y)*f;particles.push({x,y,ox:x,oy:y})}});return particles}

function Slider({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(n:number)=>void}){
 const pct=(value-min)/(max-min)*100
 return <label className="parameter"><span><i>{label}</i><output>{value.toFixed(step<.1?2:1)}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} style={{'--p':pct+'%'} as React.CSSProperties} onChange={e=>onChange(+e.target.value)}/><small><b>{min}</b><b>{max}</b></small></label>
}

function ColorPicker({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState(value),pending=useRef<string|null>(null),timer=useRef<number|null>(null)
 useEffect(()=>setDraft(value),[value])
 useEffect(()=>()=>{if(timer.current!==null)window.clearTimeout(timer.current)},[])
 const queue=(next:string)=>{setDraft(next);pending.current=next;if(timer.current===null)timer.current=window.setTimeout(()=>{timer.current=null;if(pending.current!==null){onChange(pending.current);pending.current=null}},34)}
 const hsv=hexToHsv(draft),pure=hsvToHex(hsv.h,1,1),alpha=colorAlpha(draft)
 const setColor=(hex:string)=>queue(withAlpha(hex,alpha))
 const setSv=(e:React.PointerEvent<HTMLDivElement>)=>{e.currentTarget.setPointerCapture?.(e.pointerId);const r=e.currentTarget.getBoundingClientRect(),s=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),v=1-Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));setColor(hsvToHex(hsv.h,s,v))}
 return <div className="color-picker"><button type="button" className="color-trigger" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><span className="swatch" style={{background:draft}}/><span><b>{label}</b><small>{draft}</small></span><i>{open?'−':'+'}</i></button>{open&&<div className="picker-pop"><div className="picker-head"><strong>Colour picker</strong><span>{draft}</span></div><div className="picker-surface"><div className="picker-preview" style={{background:draft}}/><div className="sv-plane" style={{'--hue':pure} as React.CSSProperties} onPointerDown={setSv} onPointerMove={e=>{if(e.buttons)setSv(e)}}><span style={{left:`${hsv.s*100}%`,top:`${(1-hsv.v)*100}%`,background:draft}}/></div></div><div className="hue-row"><span className="hue-dot" style={{background:pure}}/><input className="hue" aria-label={`${label} hue`} type="range" min="0" max="360" value={hsv.h} style={{'--picked':pure} as React.CSSProperties} onChange={e=>setColor(hsvToHex(+e.target.value,hsv.s,hsv.v))}/></div><div className="alpha-row"><span>Opacity</span><input aria-label={`${label} opacity`} type="range" min="0" max="1" step=".01" value={alpha} onChange={e=>queue(withAlpha(draft,+e.target.value))}/><output>{Math.round(alpha*100)}%</output></div></div>}</div>
}

function drawPattern(ctx:CanvasRenderingContext2D,region:PatternRegion,w:number,h:number){
 const x=region.x*w,y=region.y*h,rw=region.w*w,rh=region.h*h,gap=Math.max(5,region.scale),span=Math.hypot(rw,rh)*1.2,phase=region.phase%gap,thickness=Math.max(.5,region.thickness)
 ctx.save();ctx.beginPath();ctx.rect(x,y,rw,rh);ctx.clip();ctx.globalAlpha=region.opacity;ctx.fillStyle=region.color;ctx.strokeStyle=region.color;ctx.lineWidth=thickness;ctx.lineCap='round';ctx.translate(x+rw/2,y+rh/2);ctx.rotate(region.angle*Math.PI/180)
 const lines=(turn=false)=>{ctx.save();if(turn)ctx.rotate(Math.PI/2);for(let p=-span+phase;p<=span;p+=gap){ctx.beginPath();ctx.moveTo(p,-span);ctx.lineTo(p,span);ctx.stroke()}ctx.restore()}
 if(region.type==='stripes')lines()
 else if(region.type==='grid'){ctx.save();ctx.rotate(-region.angle*Math.PI/180);lines();lines(true);ctx.restore()}
 else if(region.type==='crosshatch'){lines();lines(true)}
 else if(region.type==='blocks'){for(let yy=-span+phase,row=0;yy<span;yy+=gap,row++)for(let xx=-span+phase,col=0;xx<span;xx+=gap,col++)if((row+col)%2===0){const size=Math.min(gap,thickness*2);ctx.fillRect(xx,yy,size,size)}}
 else if(region.type==='dots'){for(let yy=-span+phase;yy<span;yy+=gap)for(let xx=-span+phase;xx<span;xx+=gap){ctx.beginPath();ctx.arc(xx,yy,thickness,0,Math.PI*2);ctx.fill()}}
 else if(region.type==='rings'){for(let r=Math.max(1,phase);r<span;r+=gap){ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.stroke()}}
 else {const amplitude=gap*.34;for(let yy=-span+phase;yy<span;yy+=gap){ctx.beginPath();for(let xx=-span;xx<=span;xx+=4){const py=yy+Math.sin((xx+region.phase*3)/gap*Math.PI*2)*amplitude;xx===-span?ctx.moveTo(xx,py):ctx.lineTo(xx,py)}ctx.stroke()}}
 ctx.restore()
}

const Canvas=memo(function Canvas({points,setPoints,eyes,setEyes,regions,setRegions,selectedRegion,pressure,stiffness,smoothing,contourLength,visual,patternEdgeMargin,patternEyeMargin,paused,structure}:{points:P[];setPoints:React.Dispatch<React.SetStateAction<P[]>>;eyes:P[];setEyes:React.Dispatch<React.SetStateAction<P[]>>;regions:PatternRegion[];setRegions:React.Dispatch<React.SetStateAction<PatternRegion[]>>;selectedRegion:number;pressure:number;stiffness:number;smoothing:number;contourLength:number;visual:React.MutableRefObject<VisualStyle>;patternEdgeMargin:number;patternEyeMargin:number;paused:boolean;structure:number}){
 const ref=useRef<HTMLCanvasElement>(null), body=useRef<Particle[]>([]), size=useRef({w:0,h:0}), visualPoints=useRef(points.map(p=>({...p}))), mouse=useRef({x:0,y:0}), drag=useRef<{kind:'corner'|'eye'|'region';index:number}|null>(null), state=useRef({points,eyes,regions,selectedRegion,pressure,stiffness,smoothing,contourLength,patternEdgeMargin,patternEyeMargin,paused,structure})
 useEffect(()=>{state.current={points,eyes,regions,selectedRegion,pressure,stiffness,smoothing,contourLength,patternEdgeMargin,patternEyeMargin,paused,structure}},[points,eyes,regions,selectedRegion,pressure,stiffness,smoothing,contourLength,patternEdgeMargin,patternEyeMargin,paused,structure])
 useEffect(()=>{const c=ref.current!,ctx=c.getContext('2d')!;let frame=0;const layer=document.createElement('canvas'),lctx=layer.getContext('2d')!
  const trackMouse=(event:PointerEvent)=>{const r=c.getBoundingClientRect();mouse.current={x:event.clientX-r.left,y:event.clientY-r.top}}
  window.addEventListener('pointermove',trackMouse)
  const resize=()=>{const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);c.width=r.width*d;c.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);layer.width=c.width;layer.height=c.height;lctx.setTransform(d,0,0,d,0,0);if(!body.current.length||size.current.w!==r.width)body.current=build(visualPoints.current,r.width,r.height);size.current={w:r.width,h:r.height}}
  const ro=new ResizeObserver(()=>requestAnimationFrame(resize));ro.observe(c);resize()
  const loop=()=>{const {w,h}=size.current,s=state.current,v=visual.current,b=body.current;visualPoints.current.forEach((p,i)=>{p.x+=(s.points[i].x-p.x)*.2;p.y+=(s.points[i].y-p.y)*.2});const geometry=layout(visualPoints.current,w,h);if(!s.paused&&b.length){
   const {frame,counts,anchors}=geometry
   const rest=counts.flatMap((count,side)=>{const a=frame[side],z=frame[(side+1)%4],length=Math.hypot(z.x-a.x,z.y-a.y)/count*s.contourLength;return Array(count).fill(length)})
   b.forEach(p=>{const vx=(p.x-p.ox)*.9,vy=(p.y-p.oy)*.9;p.ox=p.x;p.oy=p.y;p.x+=vx;p.y+=vy})
   const constraintPasses=4+Math.round(s.stiffness*.4),constraintStrength=Math.min(.46,.08+s.stiffness*.012)
   for(let q=0;q<constraintPasses;q++){
    for(let i=0;i<N;i++){const a=b[i],z=b[(i+1)%N],dx=z.x-a.x,dy=z.y-a.y,d=Math.hypot(dx,dy)||1,k=(d-rest[i])/d*constraintStrength;a.x+=dx*k;a.y+=dy*k;z.x-=dx*k;z.y-=dy*k}
    for(let i=0;i<N;i++){const p=b[i],a=b[(i+N-1)%N],z=b[(i+1)%N];p.x+=((a.x+z.x)/2-p.x)*s.smoothing*.03;p.y+=((a.y+z.y)/2-p.y)*s.smoothing*.03}
    frame.forEach((p,i)=>{const anchor=b[anchors[i]];anchor.x+=(p.x-anchor.x)*.86;anchor.y+=(p.y-anchor.y)*.86;anchor.ox=anchor.x;anchor.oy=anchor.y})
   }
   const mid=b.reduce((a,p)=>({x:a.x+p.x/N,y:a.y+p.y/N}),{x:0,y:0});b.forEach(p=>{const dx=p.x-mid.x,dy=p.y-mid.y,d=Math.hypot(dx,dy)||1;p.x+=dx/d*s.pressure*.025;p.y+=dy/d*s.pressure*.025})}
   ctx.clearRect(0,0,w,h);const glow=ctx.createRadialGradient(w/2,h/2,10,w/2,h/2,Math.max(w,h)*.45);glow.addColorStop(0,'rgba(124,255,191,.06)');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h)
   if(b.length){const last=b[N-1],first=b[0],shape=new Path2D();shape.moveTo((last.x+first.x)/2,(last.y+first.y)/2);for(let i=0;i<N;i++){const p=b[i],z=b[(i+1)%N];shape.quadraticCurveTo(p.x,p.y,(p.x+z.x)/2,(p.y+z.y)/2)}shape.closePath();const fill=ctx.createLinearGradient(0,0,w,h);fill.addColorStop(0,hexAlpha(v.fillColor,.38));fill.addColorStop(1,hexAlpha(v.fillColor,.22));ctx.fillStyle=fill;ctx.fill(shape);lctx.clearRect(0,0,w,h);lctx.save();lctx.clip(shape);s.regions.forEach(region=>drawPattern(lctx,region,w,h));lctx.restore();lctx.save();lctx.globalCompositeOperation='destination-out';lctx.lineWidth=s.patternEdgeMargin*2;lctx.lineJoin='round';lctx.stroke(shape);s.eyes.forEach(eye=>{lctx.beginPath();lctx.arc(eye.x*w,eye.y*h,32+s.patternEyeMargin,0,Math.PI*2);lctx.fill()});lctx.restore();ctx.drawImage(layer,0,0,layer.width,layer.height,0,0,w,h);ctx.shadowColor=hexAlpha(v.outlineColor,.45);ctx.shadowBlur=28;ctx.strokeStyle=v.outlineColor;ctx.lineWidth=v.lineWidth;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke(shape);ctx.shadowBlur=0;s.regions.forEach(region=>{if(region.id!==s.selectedRegion)return;ctx.save();ctx.setLineDash([4,4]);ctx.strokeStyle=hexAlpha(v.outlineColor,.65);ctx.lineWidth=1;ctx.strokeRect(region.x*w,region.y*h,region.w*w,region.h*h);[[region.x,region.y],[region.x+region.w,region.y],[region.x+region.w,region.y+region.h],[region.x,region.y+region.h]].forEach(([hx,hy])=>{ctx.beginPath();ctx.arc(hx*w,hy*h,6,0,Math.PI*2);ctx.fillStyle=v.outlineColor;ctx.fill();ctx.strokeStyle='#071014';ctx.stroke()});ctx.restore()})}
   s.eyes.forEach((eye,index)=>{const x=eye.x*w,y=eye.y*h,r=32,dx=mouse.current.x-x,dy=mouse.current.y-y,d=Math.hypot(dx,dy)||1,pupil=Math.min(v.pupilSize,r-v.eyeLineWidth-2),travel=Math.max(0,r-pupil-v.eyeLineWidth-3),px=x+dx/d*Math.min(travel,d*.16),py=y+dy/d*Math.min(travel,d*.16);ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=v.eyeFill;ctx.fill();ctx.lineWidth=v.eyeLineWidth;ctx.strokeStyle=v.eyeOutline;ctx.stroke();ctx.beginPath();ctx.arc(px,py,pupil,0,Math.PI*2);ctx.fillStyle=v.pupilColor;ctx.shadowColor=hexAlpha(v.pupilColor,.35);ctx.shadowBlur=8;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle=hexAlpha(v.eyeOutline,.65);ctx.font='7px DM Mono, monospace';ctx.fillText(`EYE 0${index+1}`,x-r,y+r+13);ctx.restore()})
   if(s.structure>.005){ctx.save();ctx.globalAlpha=s.structure;ctx.lineWidth=1;ctx.lineCap='butt';ctx.lineJoin='miter';ctx.setLineDash([2,7]);ctx.strokeStyle='rgba(167,255,213,.55)';ctx.beginPath();visualPoints.current.forEach((p,i)=>i?ctx.lineTo(p.x*w,p.y*h):ctx.moveTo(p.x*w,p.y*h));ctx.closePath();ctx.stroke();ctx.setLineDash([]);visualPoints.current.forEach((p,i)=>{const x=p.x*w,y=p.y*h;ctx.beginPath();ctx.arc(x,y,14,0,7);ctx.fillStyle='#081114';ctx.fill();ctx.strokeStyle='#527a69';ctx.lineWidth=1;ctx.stroke();ctx.beginPath();ctx.arc(x,y,5,0,7);ctx.fillStyle='#b5ffda';ctx.shadowColor='#7cffbf';ctx.shadowBlur=14;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#9ac7b4';ctx.font='9px monospace';ctx.fillText('0'+(i+1),x+20,y+3)});ctx.restore()}frame=requestAnimationFrame(loop)};loop();return()=>{window.removeEventListener('pointermove',trackMouse);ro.disconnect();cancelAnimationFrame(frame)}},[])
 const pos=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,w:r.width,h:r.height}}
 return <canvas ref={ref} aria-label="Interactief canvas; versleep lichaams-, oog- en regiohoeken" onPointerDown={e=>{const m=pos(e),region=regions.find(r=>r.id===selectedRegion),handles=region?[[region.x,region.y],[region.x+region.w,region.y],[region.x+region.w,region.y+region.h],[region.x,region.y+region.h]]:[],regionCorner=handles.findIndex(([x,y])=>Math.hypot(x*m.w-m.x,y*m.h-m.y)<18),eye=eyes.findIndex(p=>Math.hypot(p.x*m.w-m.x,p.y*m.h-m.y)<38),corner=points.findIndex(p=>Math.hypot(p.x*m.w-m.x,p.y*m.h-m.y)<28);if(regionCorner>=0)drag.current={kind:'region',index:regionCorner};else if(eye>=0)drag.current={kind:'eye',index:eye};else if(corner>=0)drag.current={kind:'corner',index:corner};if(drag.current)e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;const m=pos(e),x=Math.max(.02,Math.min(.98,m.x/m.w)),y=Math.max(.02,Math.min(.98,m.y/m.h));if(drag.current.kind==='eye'){const i=drag.current.index;setEyes(a=>a.map((p,j)=>j===i?{x,y}:p));return}if(drag.current.kind==='region'){const i=drag.current.index;setRegions(all=>all.map(r=>{if(r.id!==selectedRegion)return r;const right=r.x+r.w,bottom=r.y+r.h,min=.03;if(i===0)return{...r,x:Math.min(x,right-min),y:Math.min(y,bottom-min),w:right-Math.min(x,right-min),h:bottom-Math.min(y,bottom-min)};if(i===1)return{...r,y:Math.min(y,bottom-min),w:Math.max(min,x-r.x),h:bottom-Math.min(y,bottom-min)};if(i===2)return{...r,w:Math.max(min,x-r.x),h:Math.max(min,y-r.y)};return{...r,x:Math.min(x,right-min),w:right-Math.min(x,right-min),h:Math.max(min,y-r.y)}}));return}const i=drag.current.index,setX=Math.max(.07,Math.min(.93,x)),setY=Math.max(.08,Math.min(.92,y));setPoints(a=>{const next=a.map(p=>({...p}));next[i]={x:setX,y:setY};next[(i+1)%4][i%2===0?'y':'x']=i%2===0?setY:setX;next[(i+3)%4][i%2===0?'x':'y']=i%2===0?setX:setY;return next})}} onPointerUp={()=>drag.current=null}/>
})

export default function App(){const [points,setPoints]=useState(INITIAL),[eyes,setEyes]=useState<P[]>([{x:.42,y:.43},{x:.58,y:.43}]),[regions,setRegions]=useState<PatternRegion[]>([{id:1,x:.28,y:.57,w:.44,h:.22,type:'stripes',color:'#D8FF73B3',scale:18,opacity:1,angle:45,thickness:6,phase:0}]),[selectedRegion,setSelectedRegion]=useState(1),[patternEdgeMargin,setPatternEdgeMargin]=useState(12),[patternEyeMargin,setPatternEyeMargin]=useState(10),[pressure,setPressure]=useState(2),[stiffness,setStiffness]=useState(14),[smoothing,setSmoothing]=useState(.42),[contourLength,setContourLength]=useState(1),[lineWidth,setLineWidth]=useState(DEFAULT_VISUAL.lineWidth),[outlineColor,setOutlineColor]=useState(DEFAULT_VISUAL.outlineColor),[fillColor,setFillColor]=useState(DEFAULT_VISUAL.fillColor),[eyeOutline,setEyeOutline]=useState(DEFAULT_VISUAL.eyeOutline),[eyeFill,setEyeFill]=useState(DEFAULT_VISUAL.eyeFill),[pupilColor,setPupilColor]=useState(DEFAULT_VISUAL.pupilColor),[eyeLineWidth,setEyeLineWidth]=useState(DEFAULT_VISUAL.eyeLineWidth),[pupilSize,setPupilSize]=useState(DEFAULT_VISUAL.pupilSize),[paused,setPaused]=useState(false),[structure,setStructure]=useState(.7),visual=useRef<VisualStyle>({...DEFAULT_VISUAL})
 const changeVisual=<K extends keyof VisualStyle>(key:K,value:VisualStyle[K],setter:React.Dispatch<React.SetStateAction<VisualStyle[K]>>)=>{visual.current[key]=value;setter(value)}
 const reset=()=>{visual.current={...DEFAULT_VISUAL};setPoints(INITIAL.map(p=>({...p})));setEyes([{x:.42,y:.43},{x:.58,y:.43}]);setRegions([{id:1,x:.28,y:.57,w:.44,h:.22,type:'stripes',color:'#D8FF73B3',scale:18,opacity:1,angle:45,thickness:6,phase:0}]);setSelectedRegion(1);setPatternEdgeMargin(12);setPatternEyeMargin(10);setPressure(2);setStiffness(14);setSmoothing(.42);setContourLength(1);setLineWidth(DEFAULT_VISUAL.lineWidth);setOutlineColor(DEFAULT_VISUAL.outlineColor);setFillColor(DEFAULT_VISUAL.fillColor);setEyeOutline(DEFAULT_VISUAL.eyeOutline);setEyeFill(DEFAULT_VISUAL.eyeFill);setPupilColor(DEFAULT_VISUAL.pupilColor);setEyeLineWidth(DEFAULT_VISUAL.eyeLineWidth);setPupilSize(DEFAULT_VISUAL.pupilSize);setStructure(.7);setPaused(false)}
 const randomizeColors=()=>{const hue=Math.random()*360,next={...visual.current,outlineColor:hslHex(hue,1,.8),fillColor:hslHex(hue,Math.random()*.2+.38,.38,.9),eyeOutline:hslHex(hue+55,.9,.85),eyeFill:hslHex(hue+180,.38,.17),pupilColor:hslHex(hue+210,.75,.08)};visual.current=next;setOutlineColor(next.outlineColor);setFillColor(next.fillColor);setEyeOutline(next.eyeOutline);setEyeFill(next.eyeFill);setPupilColor(next.pupilColor);setRegions(all=>all.map((r,i)=>({...r,color:hslHex(hue+95+i*47,.78,.66,colorAlpha(r.color))})))}
 const active=regions.find(r=>r.id===selectedRegion)??regions[0]
 const updateRegion=(patch:Partial<PatternRegion>)=>setRegions(all=>all.map(r=>r.id===selectedRegion?{...r,...patch}:r))
 const addRegion=()=>{const id=Math.max(0,...regions.map(r=>r.id))+1;setRegions(all=>[...all,{id,x:.3,y:.3,w:.4,h:.2,type:'dots',color:'#FF8DC7B3',scale:20,opacity:1,angle:0,thickness:5,phase:0}]);setSelectedRegion(id)}
 return <main><header><div className="brand"><b>S/S</b>SOUL_SPAWN</div><div className="spec"><small>SPECIMEN</small>Creature 01</div><nav><button onClick={reset}>↺ RESET</button><button className="pause" onClick={()=>setPaused(v=>!v)}>{paused?'▶ RESUME':'Ⅱ PAUSE'}</button></nav></header>
 <div className="workspace"><aside><div className="panel-title"><span>BODY PARAMETERS</span><small>+ PATTERNS</small></div>
 <Control n="01" title="Shape" tag="FORM"><Slider label="Length × perimeter" value={contourLength} min={.5} max={1.5} step={.01} onChange={setContourLength}/></Control>
 <Control n="02" title="Physics" tag="FORCE"><Slider label="Pressure" value={pressure} min={-6} max={10} step={.1} onChange={setPressure}/><Slider label="Stiffness" value={stiffness} min={1} max={30} step={.5} onChange={setStiffness}/><Slider label="Smoothing" value={smoothing} min={0} max={1} step={.01} onChange={setSmoothing}/></Control>
 <Control n="03" title="Body" tag="COLOR"><button type="button" className="randomize" onClick={randomizeColors}>✦ Randomize all colors</button><ColorPicker label="Outline" value={outlineColor} onChange={value=>changeVisual('outlineColor',value,setOutlineColor)}/><ColorPicker label="Body fill" value={fillColor} onChange={value=>changeVisual('fillColor',value,setFillColor)}/><Slider label="Line width" value={lineWidth} min={.5} max={15} step={.5} onChange={value=>changeVisual('lineWidth',value,setLineWidth)}/><Slider label="Control points" value={structure} min={0} max={1} step={.01} onChange={setStructure}/></Control>
 <Control n="04" title="Eyes" tag="DRAG TO MOVE"><ColorPicker label="Eye outline" value={eyeOutline} onChange={value=>changeVisual('eyeOutline',value,setEyeOutline)}/><ColorPicker label="Eye fill" value={eyeFill} onChange={value=>changeVisual('eyeFill',value,setEyeFill)}/><ColorPicker label="Pupil" value={pupilColor} onChange={value=>changeVisual('pupilColor',value,setPupilColor)}/><Slider label="Eye outline width" value={eyeLineWidth} min={.5} max={15} step={.5} onChange={value=>changeVisual('eyeLineWidth',value,setEyeLineWidth)}/><Slider label="Pupil size" value={pupilSize} min={2} max={24} step={1} onChange={value=>changeVisual('pupilSize',value,setPupilSize)}/></Control>
 <Control n="05" title="Patterns" tag="DRAG CORNERS"><div className="region-actions"><select aria-label="Pattern region" value={selectedRegion} onChange={e=>setSelectedRegion(+e.target.value)}>{regions.map((r,i)=><option key={r.id} value={r.id}>Region {i+1}</option>)}</select><button type="button" onClick={addRegion}>＋</button><button type="button" disabled={regions.length===1} onClick={()=>{const remaining=regions.filter(r=>r.id!==selectedRegion);setRegions(remaining);setSelectedRegion(remaining[0].id)}}>−</button></div>{active&&<><select className="pattern-type" aria-label="Pattern type" value={active.type} onChange={e=>updateRegion({type:e.target.value as PatternRegion['type']})}><option value="stripes">Stripes</option><option value="blocks">Blocks</option><option value="dots">Dots</option><option value="grid">Grid</option><option value="crosshatch">Crosshatch</option><option value="rings">Rings</option><option value="waves">Waves</option></select><ColorPicker label="Pattern color" value={active.color} onChange={color=>updateRegion({color})}/><Slider label="Spacing" value={active.scale} min={5} max={50} step={1} onChange={scale=>updateRegion({scale})}/><Slider label="Thickness" value={active.thickness} min={.5} max={20} step={.5} onChange={thickness=>updateRegion({thickness})}/><Slider label="Angle" value={active.angle} min={0} max={180} step={1} onChange={angle=>updateRegion({angle})}/><Slider label="Offset" value={active.phase} min={0} max={50} step={1} onChange={phase=>updateRegion({phase})}/></>}<Slider label="Contour margin" value={patternEdgeMargin} min={0} max={50} step={1} onChange={setPatternEdgeMargin}/><Slider label="Eye margin" value={patternEyeMargin} min={0} max={50} step={1} onChange={setPatternEyeMargin}/></Control>
 </aside><section className="stage"><div className="meta"><span>FORM / 001</span><span>PATTERN BOUNDARY ACTIVE</span></div><div className="canvas"><Canvas {...{points,setPoints,eyes,setEyes,regions,setRegions,selectedRegion,pressure,stiffness,smoothing,contourLength,visual,patternEdgeMargin,patternEyeMargin,paused,structure}}/><div className="hint"><b>⌁</b><span><strong>Drag corners or eyes</strong><small>Selected region has four handles</small></span></div></div><footer><span><i className={paused?'off':''}/> {paused?'SIMULATION PAUSED':'LIVE SIMULATION'}</span><span>REGIONS <b>{regions.length}</b>　 ACTIVE <b>{selectedRegion}</b></span></footer></section></div></main>}
function Control({n,title,tag,children}:{n:string;title:string;tag:string;children:React.ReactNode}){return <section className="control"><div className="label"><span>{n}</span><b>{title}</b><i>{tag}</i></div>{children}</section>}
