import { memo, useEffect, useImperativeHandle, useRef, useState } from 'react'
import './App.css'
import './patterns.css'
import './settings.css'
import { withCuts, sampleGeometry, patternEnvelope, baseLayout as layout } from './cuts'
import type { Cut } from './cuts'
import { CutSettings, CutOverlay } from './CutEditor'
import type { CutEditorState } from './CutEditor'
import Viewport from './Viewport'
import { MultiSelect, SelectionBar } from './MultiSelect'
import { useMultiControl } from './useMultiControl'
import SaveDialog from './SaveDialog'
import { saveToProject } from './saveFile'
import { parseDesign, serializeDesign } from './projectFile'
import type { Design, SavedParticle, SavedView, VisualStyle } from './projectFile'
import { createPatternRenderer, defaults, initialRegion } from './naturalPatterns'
import type { PatternRegion } from './naturalPatterns'
import { PatternEditorOverlay } from './PatternEditorOverlay'

type P={x:number;y:number}; type Particle=P&{ox:number;oy:number}
const INITIAL:P[]=[{x:.3,y:.29},{x:.7,y:.29},{x:.7,y:.7},{x:.3,y:.7}]
const DEFAULT_VISUAL:VisualStyle={lineWidth:3,outlineColor:'#A7FFD5FF',fillColor:'#4A9D91E8',backgroundColor:'#071014FF',eyeOutline:'#D8FFF0FF',eyeFill:'#173A3EFF',pupilColor:'#071014FF',eyeLineWidth:4,pupilSize:9}
function hsvToHex(h:number,s:number,v:number){const c=v*s,hp=((h%360)+360)%360/60,x=c*(1-Math.abs(hp%2-1));let rgb=[0,0,0];if(hp<1)rgb=[c,x,0];else if(hp<2)rgb=[x,c,0];else if(hp<3)rgb=[0,c,x];else if(hp<4)rgb=[0,x,c];else if(hp<5)rgb=[x,0,c];else rgb=[c,0,x];const m=v-c;return '#'+rgb.map(n=>Math.round((n+m)*255).toString(16).padStart(2,'0')).join('').toUpperCase()}
function hexToHsv(hex:string){const n=parseInt(hex.slice(1,7),16),r=(n>>16&255)/255,g=(n>>8&255)/255,b=(n&255)/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d){if(max===r)h=60*((g-b)/d%6);else if(max===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4)}return{h:(h+360)%360,s:max?d/max:0,v:max}}
function colorAlpha(hex:string){return hex.length>=9?parseInt(hex.slice(7,9),16)/255:1}
function controlContrast(hex:string){const n=parseInt(hex.slice(1,7),16),linear=(value:number)=>{const c=value/255;return c<=.04045?c/12.92:Math.pow((c+.055)/1.055,2.4)},l=.2126*linear(n>>16&255)+.7152*linear(n>>8&255)+.0722*linear(n&255);return l>.38?'#071014':'#B5FFDA'}
function withAlpha(hex:string,alpha:number){return hex.slice(0,7)+Math.round(alpha*255).toString(16).padStart(2,'0').toUpperCase()}
function hexAlpha(hex:string,alpha:number){const n=parseInt(hex.slice(1,7),16);return `rgba(${n>>16&255},${n>>8&255},${n&255},${alpha*colorAlpha(hex)})`}
function hslHex(h:number,s:number,l:number,alpha=1){const a=s*Math.min(l,1-l),f=(n:number)=>{const k=(n+h/30)%12,c=l-a*Math.max(-1,Math.min(k-3,9-k,1));return Math.round(255*c).toString(16).padStart(2,'0')};return `#${f(0)}${f(8)}${f(4)}${Math.round(alpha*255).toString(16).padStart(2,'0')}`.toUpperCase()}
function build(points:P[],w:number,h:number):Particle[]{const {frame,counts}=layout(points,w,h),particles:Particle[]=[];counts.forEach((count,side)=>{const a=frame[side],b=frame[(side+1)%4];for(let i=0;i<count;i++){const f=i/count,x=a.x+(b.x-a.x)*f,y=a.y+(b.y-a.y)*f;particles.push({x,y,ox:x,oy:y})}});return particles}

function Slider({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(n:number)=>void}){
 const multi=useMultiControl({kind:'slider',value,min,max,step,change:onChange})
 const pct=(value-min)/(max-min)*100
 return <label className="parameter" data-selected={multi.selected} {...multi.events} title="Ctrl + klik om te selecteren"><span><i>{label}</i><output>{value.toFixed(step<.1?2:1)}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} style={{'--p':pct+'%'} as React.CSSProperties} onChange={e=>multi.slider(+e.target.value)}/><small><b>{min}</b><b>{max}</b></small></label>
}

function ColorPicker({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){
 const multi=useMultiControl({kind:'color',value,change:onChange})
 const initial=hexToHsv(value),[open,setOpen]=useState(false),[draft,setDraft]=useState(value),[hsv,setHsv]=useState(initial),emitted=useRef<string|null>(null),pickerRef=useRef<HTMLDivElement>(null),colorFrame=useRef<number|null>(null),pendingColor=useRef<string|null>(null)
 useEffect(()=>{if(!open)return;const close=(event:PointerEvent)=>{if(!pickerRef.current?.contains(event.target as Node))setOpen(false)};window.addEventListener('pointerdown',close,true);return()=>window.removeEventListener('pointerdown',close,true)},[open])
 useEffect(()=>{setDraft(value);if(emitted.current===value){emitted.current=null;return}const next=hexToHsv(value);setHsv(current=>next.s>.001&&next.v>.001?next:{...next,h:current.h})},[value])
 useEffect(()=>()=>{if(colorFrame.current!==null)cancelAnimationFrame(colorFrame.current)},[])
 const queue=(next:string)=>{setDraft(next);emitted.current=next;pendingColor.current=next;if(colorFrame.current!==null)return;colorFrame.current=requestAnimationFrame(()=>{colorFrame.current=null;const color=pendingColor.current;pendingColor.current=null;if(color)multi.color(color)})}
 const pure=hsvToHex(hsv.h,1,1),alpha=colorAlpha(draft)
 const setColor=(hex:string)=>queue(withAlpha(hex,alpha))
 const setSv=(e:React.PointerEvent<HTMLDivElement>)=>{e.currentTarget.setPointerCapture?.(e.pointerId);const r=e.currentTarget.getBoundingClientRect(),s=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),v=1-Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));setHsv(current=>({...current,s,v}));setColor(hsvToHex(hsv.h,s,v))}
 const setHue=(next:number)=>{setHsv(current=>({...current,h:next}));setColor(hsvToHex(next,hsv.s,hsv.v))}
 return <div ref={pickerRef} className="color-picker" data-selected={multi.selected} {...multi.events} title="Ctrl + klik om te selecteren"><button type="button" className="color-trigger" aria-expanded={open} aria-pressed={multi.selected} onClick={()=>setOpen(v=>!v)}><span className="swatch" style={{background:draft}}/><span><b>{label}</b><small>{draft}</small></span><i>{open?'−':'+'}</i></button>{open&&<div className="picker-pop"><div className="picker-head"><strong>Colour picker</strong><span>{draft}</span></div><div className="picker-surface"><div className="picker-preview" style={{background:draft}}/><div className="sv-plane" style={{'--hue':pure} as React.CSSProperties} onPointerDown={setSv} onPointerMove={e=>{if(e.buttons)setSv(e)}}><span style={{left:`${hsv.s*100}%`,top:`${(1-hsv.v)*100}%`,background:draft}}/></div></div><div className="hue-row"><span className="hue-dot" style={{background:pure}}/><input className="hue" aria-label={`${label} hue`} type="range" min="0" max="360" value={hsv.h} style={{'--picked':pure} as React.CSSProperties} onChange={e=>setHue(+e.target.value)}/></div><div className="alpha-row"><span>Opacity</span><input aria-label={`${label} opacity`} type="range" min="0" max="1" step=".01" value={alpha} onChange={e=>queue(withAlpha(draft,+e.target.value))}/><output>{Math.round(alpha*100)}%</output></div></div>}</div>
}

const Canvas=memo(function Canvas({initialBody,bodyCapture,points,setPoints,eyes,setEyes,regions,setRegions,selectedRegion,pressure,stiffness,smoothing,contourLength,visual,backgroundColor,patternEdgeMargin,patternEyeMargin,paused,structure,cuts}:{cuts:Cut[];initialBody?:SavedParticle[];bodyCapture:React.MutableRefObject<(()=>SavedParticle[])|null>;points:P[];setPoints:React.Dispatch<React.SetStateAction<P[]>>;eyes:P[];setEyes:React.Dispatch<React.SetStateAction<P[]>>;regions:PatternRegion[];setRegions:React.Dispatch<React.SetStateAction<PatternRegion[]>>;selectedRegion:number;pressure:number;stiffness:number;smoothing:number;contourLength:number;visual:React.MutableRefObject<VisualStyle>;backgroundColor:string;patternEdgeMargin:number;patternEyeMargin:number;paused:boolean;structure:number}){
 const svgRef=useRef<SVGSVGElement>(null),exportRef=useRef<(()=>void)|null>(null),ref=useRef<HTMLCanvasElement>(null), body=useRef<Particle[]>([]), size=useRef({w:0,h:0}), visualPoints=useRef(points.map(p=>({...p}))), mouse=useRef({x:0,y:0}), drag=useRef<{kind:'corner'|'eye'|'region';index:number}|null>(null), state=useRef({points,eyes,regions,selectedRegion,pressure,stiffness,smoothing,contourLength,patternEdgeMargin,patternEyeMargin,paused,structure,cuts})
 useEffect(()=>{state.current={points,eyes,regions,selectedRegion,pressure,stiffness,smoothing,contourLength,patternEdgeMargin,patternEyeMargin,paused,structure,cuts}},[points,eyes,regions,selectedRegion,pressure,stiffness,smoothing,contourLength,patternEdgeMargin,patternEyeMargin,paused,structure,cuts])
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const cursor=(event:PointerEvent)=>{if(drag.current){canvas.style.cursor='grabbing';return}const box=canvas.getBoundingClientRect(),x=(event.clientX-box.left)*size.current.w/box.width,y=(event.clientY-box.top)*size.current.h/box.height,s=state.current,overEye=s.eyes.some(p=>Math.hypot(p.x*size.current.w-x,p.y*size.current.h-y)<38),overCorner=visualPoints.current.some(p=>Math.hypot(p.x*size.current.w-x,p.y*size.current.h-y)<28);canvas.style.cursor=s.structure>.005&&(overEye||overCorner)?'grab':'default'};const release=()=>{canvas.style.cursor='default'};canvas.addEventListener('pointermove',cursor);canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('pointerleave',release);return()=>{canvas.removeEventListener('pointermove',cursor);canvas.removeEventListener('pointerup',release);canvas.removeEventListener('pointercancel',release);canvas.removeEventListener('pointerleave',release)}},[])
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;canvas.style.background='transparent';const viewport=canvas.closest<HTMLElement>('.scene-viewport');if(viewport){viewport.style.backgroundColor=backgroundColor;viewport.style.setProperty('--control-color',controlContrast(backgroundColor))}},[backgroundColor])
 useImperativeHandle(bodyCapture,()=>()=>body.current.map(p=>({x:p.x/size.current.w,y:p.y/size.current.h,ox:p.ox/size.current.w,oy:p.oy/size.current.h})),[])
 useEffect(()=>{const c=ref.current!,ctx=c.getContext('2d')!;let frame=0;const renderer=createPatternRenderer(svgRef.current!);exportRef.current=()=>renderer.export()
  const trackMouse=(event:PointerEvent)=>{const r=c.getBoundingClientRect();mouse.current={x:(event.clientX-r.left)*size.current.w/r.width,y:(event.clientY-r.top)*size.current.h/r.height}}
  window.addEventListener('pointermove',trackMouse)
  const resize=()=>{const r={width:c.clientWidth,height:c.clientHeight},d=Math.min(devicePixelRatio,2);c.width=r.width*d;c.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);if(!body.current.length||size.current.w!==r.width)body.current=initialBody?initialBody.map(p=>({x:p.x*r.width,y:p.y*r.height,ox:p.ox*r.width,oy:p.oy*r.height})):build(visualPoints.current,r.width,r.height);size.current={w:r.width,h:r.height}}
  let geometrySignature='',cutReference=state.current.cuts,restKey='',rest:number[]=[]
  const ro=new ResizeObserver(()=>requestAnimationFrame(resize));ro.observe(c);resize()
  const loop=()=>{const {w,h}=size.current,s=state.current,v=visual.current;let b=body.current;visualPoints.current.forEach((p,i)=>{p.x+=(s.points[i].x-p.x)*.2;p.y+=(s.points[i].y-p.y)*.2});const geometry=withCuts(layout(visualPoints.current,w,h),s.cuts,w,h),cutsChanged=s.cuts!==cutReference
   if((geometrySignature&&geometrySignature!==geometry.signature)||b.length!==geometry.counts.reduce((a,n)=>a+n,0)||(s.paused&&cutsChanged)){body.current=sampleGeometry(geometry);b=body.current}
   geometrySignature=geometry.signature;cutReference=s.cuts;const N=b.length
   if(!s.paused&&b.length){
   const {frame,counts,anchors}=geometry
   const nextRestKey=`${geometry.signature}:${s.contourLength}`;if(nextRestKey!==restKey){rest=counts.flatMap((count,side)=>{const a=frame[side],z=frame[(side+1)%frame.length],length=Math.hypot(z.x-a.x,z.y-a.y)/count*s.contourLength;return Array(count).fill(length)});restKey=nextRestKey}
   b.forEach(p=>{const vx=(p.x-p.ox)*.9,vy=(p.y-p.oy)*.9;p.ox=p.x;p.oy=p.y;p.x+=vx;p.y+=vy})
   const constraintPasses=4+Math.round(s.stiffness*.4),constraintStrength=Math.min(.46,.08+s.stiffness*.012)
   for(let q=0;q<constraintPasses;q++){
    for(let i=0;i<N;i++){const a=b[i],z=b[(i+1)%N],dx=z.x-a.x,dy=z.y-a.y,d=Math.hypot(dx,dy)||1,k=(d-rest[i])/d*constraintStrength;a.x+=dx*k;a.y+=dy*k;z.x-=dx*k;z.y-=dy*k}
    for(let i=0;i<N;i++){const p=b[i],a=b[(i+N-1)%N],z=b[(i+1)%N];p.x+=((a.x+z.x)/2-p.x)*s.smoothing*.03;p.y+=((a.y+z.y)/2-p.y)*s.smoothing*.03}
    frame.forEach((p,i)=>{const anchor=b[anchors[i]];anchor.x+=(p.x-anchor.x)*.86;anchor.y+=(p.y-anchor.y)*.86;anchor.ox=anchor.x;anchor.oy=anchor.y})
   }
   const mid=b.reduce((a,p)=>({x:a.x+p.x/N,y:a.y+p.y/N}),{x:0,y:0});b.forEach(p=>{const dx=p.x-mid.x,dy=p.y-mid.y,d=Math.hypot(dx,dy)||1;p.x+=dx/d*s.pressure*.025;p.y+=dy/d*s.pressure*.025})}
   ctx.clearRect(0,0,w,h);const glow=ctx.createRadialGradient(w/2,h/2,10,w/2,h/2,Math.max(w,h)*.45);glow.addColorStop(0,'rgba(124,255,191,.06)');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h)
   if(b.length){const last=b[N-1],first=b[0],shape=new Path2D();shape.moveTo((last.x+first.x)/2,(last.y+first.y)/2);for(let i=0;i<N;i++){const p=b[i],z=b[(i+1)%N];shape.quadraticCurveTo(p.x,p.y,(p.x+z.x)/2,(p.y+z.y)/2)}shape.closePath();const fill=ctx.createLinearGradient(0,0,w,h);fill.addColorStop(0,hexAlpha(v.fillColor,1));fill.addColorStop(1,hexAlpha(v.fillColor,1));ctx.fillStyle=fill;ctx.fill(shape);renderer.render(s.regions,w,h,b,geometry.sideCounts,s.eyes,s.patternEdgeMargin,s.patternEyeMargin,patternEnvelope(b,geometry));ctx.shadowColor=hexAlpha(v.outlineColor,.45);ctx.shadowBlur=28;ctx.strokeStyle=v.outlineColor;ctx.lineWidth=v.lineWidth;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke(shape);ctx.shadowBlur=0}
   s.eyes.forEach((eye,index)=>{const x=eye.x*w,y=eye.y*h,r=32,dx=mouse.current.x-x,dy=mouse.current.y-y,d=Math.hypot(dx,dy)||1,pupil=Math.min(v.pupilSize,r-v.eyeLineWidth-2),travel=Math.max(0,r-pupil-v.eyeLineWidth-3),px=x+dx/d*Math.min(travel,d*.16),py=y+dy/d*Math.min(travel,d*.16);ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=v.eyeFill;ctx.fill();ctx.lineWidth=v.eyeLineWidth;ctx.strokeStyle=v.eyeOutline;ctx.stroke();ctx.beginPath();ctx.arc(px,py,pupil,0,Math.PI*2);ctx.fillStyle=v.pupilColor;ctx.shadowColor=hexAlpha(v.pupilColor,.35);ctx.shadowBlur=8;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle=hexAlpha(v.eyeOutline,.65);ctx.font='7px DM Mono, monospace';ctx.fillText(`EYE 0${index+1}`,x-r,y+r+13);ctx.restore()})
   if(s.structure>.005){const control=controlContrast(v.backgroundColor);ctx.save();ctx.globalAlpha=s.structure;ctx.lineWidth=1;ctx.lineCap='butt';ctx.lineJoin='miter';ctx.setLineDash([2,7]);ctx.strokeStyle=control;ctx.beginPath();visualPoints.current.forEach((p,i)=>i?ctx.lineTo(p.x*w,p.y*h):ctx.moveTo(p.x*w,p.y*h));ctx.closePath();ctx.stroke();ctx.setLineDash([]);visualPoints.current.forEach((p,i)=>{const x=p.x*w,y=p.y*h;ctx.beginPath();ctx.arc(x,y,14,0,7);ctx.fillStyle=v.backgroundColor;ctx.fill();ctx.strokeStyle=control;ctx.lineWidth=1;ctx.stroke();ctx.beginPath();ctx.arc(x,y,5,0,7);ctx.fillStyle=control;ctx.shadowColor=control;ctx.shadowBlur=10;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle=control;ctx.font='9px monospace';ctx.fillText('0'+(i+1),x+20,y+3)});ctx.restore()}frame=requestAnimationFrame(loop)};loop();return()=>{window.removeEventListener('pointermove',trackMouse);ro.disconnect();cancelAnimationFrame(frame);renderer.dispose();exportRef.current=null}},[initialBody,bodyCapture,visual])
 const pos=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*size.current.w/r.width,y:(e.clientY-r.top)*size.current.h/r.height,w:size.current.w,h:size.current.h}}
 return <><canvas style={{background:visual.current.backgroundColor}} ref={ref} aria-label="Interactief canvas; versleep lichaams-, oog- en regiohoeken" onPointerDown={e=>{const m=pos(e),region=regions.find(r=>r.id===selectedRegion),handles=region?[[region.x,region.y],[region.x+region.w,region.y],[region.x+region.w,region.y+region.h],[region.x,region.y+region.h]]:[],regionCorner=handles.findIndex(([x,y])=>Math.hypot(x*m.w-m.x,y*m.h-m.y)<18),eye=eyes.findIndex(p=>Math.hypot(p.x*m.w-m.x,p.y*m.h-m.y)<38),corner=points.findIndex(p=>Math.hypot(p.x*m.w-m.x,p.y*m.h-m.y)<28);if(regionCorner>=0)drag.current={kind:'region',index:regionCorner};else if(eye>=0)drag.current={kind:'eye',index:eye};else if(corner>=0)drag.current={kind:'corner',index:corner};if(drag.current)e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;const m=pos(e),x=Math.max(.02,Math.min(.98,m.x/m.w)),y=Math.max(.02,Math.min(.98,m.y/m.h));if(drag.current.kind==='eye'){const i=drag.current.index;setEyes(a=>a.map((p,j)=>j===i?{x,y}:p));return}if(drag.current.kind==='region'){const i=drag.current.index;setRegions(all=>all.map(r=>{if(r.id!==selectedRegion)return r;const right=r.x+r.w,bottom=r.y+r.h,min=.03;if(i===0)return{...r,x:Math.min(x,right-min),y:Math.min(y,bottom-min),w:right-Math.min(x,right-min),h:bottom-Math.min(y,bottom-min)};if(i===1)return{...r,y:Math.min(y,bottom-min),w:Math.max(min,x-r.x),h:bottom-Math.min(y,bottom-min)};if(i===2)return{...r,w:Math.max(min,x-r.x),h:Math.max(min,y-r.y)};return{...r,x:Math.min(x,right-min),w:right-Math.min(x,right-min),h:Math.max(min,y-r.y)}}));return}const i=drag.current.index,setX=Math.max(.07,Math.min(.93,x)),setY=Math.max(.08,Math.min(.92,y));setPoints(a=>{const next=a.map(p=>({...p}));next[i]={x:setX,y:setY};next[(i+1)%4][i%2===0?'y':'x']=i%2===0?setY:setX;next[(i+3)%4][i%2===0?'x':'y']=i%2===0?setX:setY;return next})}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null} onLostPointerCapture={()=>drag.current=null}/><svg ref={svgRef} aria-label="Vector skin patterns" style={{position:"absolute",inset:0,width:"100%",height:"100%",pointerEvents:"none"}}/><button type="button" className="export-pattern" onClick={()=>exportRef.current?.()}>↓ Export pattern SVG</button></>
})

export default function App(){const [points,setPoints]=useState(INITIAL),[eyes,setEyes]=useState<P[]>([{x:.42,y:.43},{x:.58,y:.43}]),[regions,setRegions]=useState<PatternRegion[]>([]),[selectedRegion,setSelectedRegion]=useState(0),[patternEdgeMargin,setPatternEdgeMargin]=useState(12),[patternEyeMargin,setPatternEyeMargin]=useState(10),[pressure,setPressure]=useState(2),[stiffness,setStiffness]=useState(14),[smoothing,setSmoothing]=useState(.42),[contourLength,setContourLength]=useState(1),[lineWidth,setLineWidth]=useState(DEFAULT_VISUAL.lineWidth),[outlineColor,setOutlineColor]=useState(DEFAULT_VISUAL.outlineColor),[fillColor,setFillColor]=useState(DEFAULT_VISUAL.fillColor),[eyeOutline,setEyeOutline]=useState(DEFAULT_VISUAL.eyeOutline),[eyeFill,setEyeFill]=useState(DEFAULT_VISUAL.eyeFill),[pupilColor,setPupilColor]=useState(DEFAULT_VISUAL.pupilColor),[eyeLineWidth,setEyeLineWidth]=useState(DEFAULT_VISUAL.eyeLineWidth),[pupilSize,setPupilSize]=useState(DEFAULT_VISUAL.pupilSize),[paused,setPaused]=useState(false),[structure,setStructure]=useState(.7),[drawing,setDrawing]=useState(false),[draft,setDraft]=useState<P[]>([]),visual=useRef<VisualStyle>({...DEFAULT_VISUAL})
 const [backgroundColor,setBackgroundColor]=useState(DEFAULT_VISUAL.backgroundColor)
 const [cuts,setCuts]=useState<Cut[]>([]),[cutEditor,setCutEditor]=useState<CutEditorState>({drawing:false,draft:null,selected:null})
 const [saving,setSaving]=useState(false),[saveName,setSaveName]=useState('Soulspawn.json'),[pendingSave,setPendingSave]=useState<string|null>(null),[saveError,setSaveError]=useState('')
 const [revision,setRevision]=useState(0),[loaded,setLoaded]=useState<Design|null>(null),[fileMessage,setFileMessage]=useState(''),[loading,setLoading]=useState(false),fileInput=useRef<HTMLInputElement>(null),bodyCapture=useRef<(()=>SavedParticle[])|null>(null),viewCapture=useRef<(()=>SavedView)|null>(null)
 const save=()=>{try{const body=bodyCapture.current?.(),view=viewCapture.current?.();if(!body||!view)throw new Error('Het ontwerp wordt nog geladen. Probeer het zo opnieuw.');const design:Design={points,cuts,eyes,regions,selectedRegion,patternEdgeMargin,patternEyeMargin,pressure,stiffness,smoothing,contourLength,visual:{...visual.current},paused,structure,body,view};const content=serializeDesign(design);parseDesign(content);setSaveError('');setPendingSave(content)}catch(error){setFileMessage(error instanceof Error?error.message:'Opslaan is niet gelukt.')}}
 const commitSave=async(name:string)=>{if(pendingSave===null||saving)return;setSaving(true);setSaveError('');try{const result=await saveToProject(pendingSave,name);setSaveName(result.name);setPendingSave(null);setFileMessage('Opgeslagen: '+result.path)}catch(error){setSaveError(error instanceof Error?error.message:'Opslaan is niet gelukt.')}finally{setSaving(false)}}

 const load=async(file:File)=>{setLoading(true);try{if(file.size>2_000_000)throw new Error('Dit bestand is te groot. Kies een Soulspawn-ontwerpbestand.');const d=parseDesign(await file.text());visual.current={...d.visual};setPoints(d.points);setCuts(d.cuts??[]);setCutEditor({drawing:false,draft:null,selected:null});setEyes(d.eyes);setRegions(d.regions);setSelectedRegion(d.selectedRegion);setPatternEdgeMargin(d.patternEdgeMargin);setPatternEyeMargin(d.patternEyeMargin);setPressure(d.pressure);setStiffness(d.stiffness);setSmoothing(d.smoothing);setContourLength(d.contourLength);setStructure(d.structure);setPaused(d.paused);setLineWidth(d.visual.lineWidth);setOutlineColor(d.visual.outlineColor);setFillColor(d.visual.fillColor);setBackgroundColor(d.visual.backgroundColor);setEyeOutline(d.visual.eyeOutline);setEyeFill(d.visual.eyeFill);setPupilColor(d.visual.pupilColor);setEyeLineWidth(d.visual.eyeLineWidth);setPupilSize(d.visual.pupilSize);setLoaded(d);setSaveName(file.name);setRevision(n=>n+1);setFileMessage('Geladen: '+file.name)}catch(error){setFileMessage(error instanceof Error?error.message:'Laden is niet gelukt.')}finally{setLoading(false)}}
 const changeVisual=<K extends keyof VisualStyle>(key:K,value:VisualStyle[K],setter:React.Dispatch<React.SetStateAction<VisualStyle[K]>>)=>{visual.current[key]=value;setter(value)}
 const reset=()=>{setCuts([]);setCutEditor({drawing:false,draft:null,selected:null});setLoaded(null);setRevision(n=>n+1);setFileMessage('');visual.current={...DEFAULT_VISUAL};setPoints(INITIAL.map(p=>({...p})));setEyes([{x:.42,y:.43},{x:.58,y:.43}]);setRegions([]);setSelectedRegion(0);setDrawing(false);setDraft([]);setPatternEdgeMargin(12);setPatternEyeMargin(10);setPressure(2);setStiffness(14);setSmoothing(.42);setContourLength(1);setLineWidth(DEFAULT_VISUAL.lineWidth);setOutlineColor(DEFAULT_VISUAL.outlineColor);setFillColor(DEFAULT_VISUAL.fillColor);setBackgroundColor(DEFAULT_VISUAL.backgroundColor);setEyeOutline(DEFAULT_VISUAL.eyeOutline);setEyeFill(DEFAULT_VISUAL.eyeFill);setPupilColor(DEFAULT_VISUAL.pupilColor);setEyeLineWidth(DEFAULT_VISUAL.eyeLineWidth);setPupilSize(DEFAULT_VISUAL.pupilSize);setStructure(.7);setPaused(false)}
 const randomizeColors=()=>{const hue=Math.random()*360,next={...visual.current,outlineColor:hslHex(hue,1,.8),fillColor:hslHex(hue,Math.random()*.2+.38,.38,.9),eyeOutline:hslHex(hue+55,.9,.85),eyeFill:hslHex(hue+180,.38,.17),pupilColor:hslHex(hue+210,.75,.08)};visual.current=next;setOutlineColor(next.outlineColor);setFillColor(next.fillColor);setEyeOutline(next.eyeOutline);setEyeFill(next.eyeFill);setPupilColor(next.pupilColor);setRegions(all=>all.map((r,i)=>({...r,color:hslHex(hue+95+i*47,.78,.66,colorAlpha(r.color))})))}
 const active=regions.find(r=>r.id===selectedRegion)??regions[0]

 const updateRegion=(patch:Partial<PatternRegion>)=>setRegions(all=>all.map(r=>r.id===selectedRegion?{...r,...patch}:r))
 const addRegion=()=>{const id=Math.max(0,...regions.map(r=>r.id))+1;setRegions(all=>[...all,{...initialRegion(),id,seed:id*17,...defaults('giraffe')}]);setSelectedRegion(id);setDraft([]);setDrawing(true)}
 return <main>{pendingSave!==null&&<SaveDialog name={saveName} busy={saving} error={saveError} onCancel={()=>setPendingSave(null)} onSave={name=>void commitSave(name)}/>}<header><div className="brand"><img src="/favicon.svg" alt=""/>Soulspawn</div><div className="spec"><small>SPECIMEN</small>Creature 01</div><nav><button onClick={()=>void save()} disabled={loading||saving}>{saving?'Saving…':'Save'}</button><button onClick={()=>fileInput.current?.click()} disabled={loading||saving}>{loading?'Loading…':'Load'}</button><input ref={fileInput} type="file" accept=".json,application/json" hidden aria-label="Load Soulspawn design" onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';if(file)void load(file)}}/><button onClick={reset}>↺ RESET</button><button className="pause" onClick={()=>setPaused(v=>!v)}>{paused?'▶ RESUME':'Ⅱ PAUSE'}</button></nav></header>
 <div className="workspace"><aside aria-label="Settings"><div className="panel-title"><h1>Settings</h1><p>Shape, appearance & patterns</p></div><MultiSelect key={`${revision}:${selectedRegion}`}><SelectionBar/><div className="parameter-grid">
 <Control title="Shape"><Slider label="Length × perimeter" value={contourLength} min={.5} max={1.5} step={.01} onChange={setContourLength}/><CutSettings points={points} bodyCapture={bodyCapture} cuts={cuts} setCuts={setCuts} editor={cutEditor} setEditor={setCutEditor}/></Control>
 <Control title="Physics"><Slider label="Pressure" value={pressure} min={-6} max={10} step={.1} onChange={setPressure}/><Slider label="Stiffness" value={stiffness} min={1} max={30} step={.5} onChange={setStiffness}/><Slider label="Smoothing" value={smoothing} min={0} max={1} step={.01} onChange={setSmoothing}/></Control>
 <Control title="Body"><ColorPicker label="Background" value={backgroundColor} onChange={value=>changeVisual('backgroundColor',value,setBackgroundColor)}/><button type="button" className="randomize" onClick={randomizeColors}>✦ Randomize all colors</button><ColorPicker label="Outline" value={outlineColor} onChange={value=>changeVisual('outlineColor',value,setOutlineColor)}/><ColorPicker label="Body fill" value={fillColor} onChange={value=>changeVisual('fillColor',value,setFillColor)}/><Slider label="Line width" value={lineWidth} min={.5} max={15} step={.5} onChange={value=>changeVisual('lineWidth',value,setLineWidth)}/></Control>
 <Control title="Eyes"><ColorPicker label="Eye outline" value={eyeOutline} onChange={value=>changeVisual('eyeOutline',value,setEyeOutline)}/><ColorPicker label="Eye fill" value={eyeFill} onChange={value=>changeVisual('eyeFill',value,setEyeFill)}/><ColorPicker label="Pupil" value={pupilColor} onChange={value=>changeVisual('pupilColor',value,setPupilColor)}/><Slider label="Eye outline width" value={eyeLineWidth} min={.5} max={15} step={.5} onChange={value=>changeVisual('eyeLineWidth',value,setEyeLineWidth)}/><Slider label="Pupil size" value={pupilSize} min={2} max={24} step={1} onChange={value=>changeVisual('pupilSize',value,setPupilSize)}/></Control>
 <Control title="Patterns"><div className="setting-caption">Region</div><div className="region-actions"><select aria-label="Pattern region" value={selectedRegion} onChange={e=>setSelectedRegion(+e.target.value)}>{regions.map((r,i)=><option key={r.id} value={r.id}>Region {i+1}</option>)}</select><button type="button" aria-label="Add pattern region" onClick={addRegion}>＋</button><button type="button" aria-label="Remove pattern region" disabled={regions.length===0} onClick={()=>{const remaining=regions.filter(r=>r.id!==selectedRegion);setRegions(remaining);setSelectedRegion(remaining[0]?.id??0)}}>−</button></div>{active&&<><div className="setting-caption">Pattern type</div><select className="pattern-type" aria-label="Pattern type" value={active.type} onChange={e=>updateRegion(defaults(e.target.value as PatternRegion['type']))}><option value="zebra">Zebra</option><option value="giraffe">Giraffe</option><option value="cow">Koe</option></select><ColorPicker label="Pattern color" value={active.color} onChange={color=>updateRegion({color})}/><Slider label={active.type==='zebra'?'Stripe density':active.type==='giraffe'?'Cell density':'Blob density'} value={active.scale} min={3} max={active.type==='zebra'?22:12} step={1} onChange={scale=>updateRegion({scale})}/><Slider label={active.type==='giraffe'?'Cell growth':'Pigment coverage'} value={active.coverage} min={.2} max={.95} step={.01} onChange={coverage=>updateRegion({coverage})}/><Slider label="Organic variation" value={active.variation} min={0} max={1} step={.01} onChange={variation=>updateRegion({variation})}/><button className="randomize" onClick={()=>updateRegion({seed:active.seed+1})}>✦ Randomize pattern</button></>}<div className="setting-caption setting-divider">Margins</div><Slider label="Contour margin" value={patternEdgeMargin} min={0} max={50} step={1} onChange={setPatternEdgeMargin}/><Slider label="Eye margin" value={patternEyeMargin} min={0} max={50} step={1} onChange={setPatternEyeMargin}/></Control>
 </div></MultiSelect></aside><section className="stage"><div className="meta"><span>FORM / 001</span><span>PATTERN BOUNDARY ACTIVE</span></div><Viewport structure={structure} onStructureChange={setStructure} instruction={cutEditor.drawing?(cutEditor.draft?"Click for depth or a bend · Enter: done · Backspace: undo · Esc: cancel":"Click the outline to start · Esc: cancel"):undefined} key={revision} initialView={loaded?.view} viewCapture={viewCapture}><PatternEditorOverlay {...{regions,setRegions,selectedRegion,drawing,setDrawing,draft,setDraft,structure}}/><Canvas initialBody={loaded?.body} bodyCapture={bodyCapture} backgroundColor={backgroundColor} {...{points,setPoints,eyes,setEyes,regions,setRegions,selectedRegion,pressure,stiffness,smoothing,contourLength,visual,patternEdgeMargin,patternEyeMargin,paused,structure,cuts}}/><CutOverlay structure={structure} cuts={cuts} setCuts={setCuts} editor={cutEditor} setEditor={setCutEditor} points={points} bodyCapture={bodyCapture}/><div className="hint"><b>⌁</b><span><strong>Drag corners or eyes</strong><small>Selected region has four handles</small></span></div></Viewport><footer><span role="status" aria-live="polite">{fileMessage||<><i className={paused?'off':''}/> {paused?'SIMULATION PAUSED':'LIVE SIMULATION'}</>}</span><span>REGIONS <b>{regions.length}</b>　 ACTIVE <b>{selectedRegion}</b></span></footer></section></div></main>}
function Control({title,children}:{title:string;children:React.ReactNode}){return <section className="control" aria-label={title}><h2 className="label">{title}</h2>{children}</section>}
