import { useEffect, useRef, useState } from 'react'
import './App.css'

type P={x:number;y:number}; type Particle=P&{ox:number;oy:number}
const INITIAL:P[]=[{x:.3,y:.29},{x:.7,y:.29},{x:.7,y:.7},{x:.3,y:.7}]
const N=64
function hsvToHex(h:number,s:number,v:number){const c=v*s,hp=((h%360)+360)%360/60,x=c*(1-Math.abs(hp%2-1));let rgb=[0,0,0];if(hp<1)rgb=[c,x,0];else if(hp<2)rgb=[x,c,0];else if(hp<3)rgb=[0,c,x];else if(hp<4)rgb=[0,x,c];else if(hp<5)rgb=[x,0,c];else rgb=[c,0,x];const m=v-c;return '#'+rgb.map(n=>Math.round((n+m)*255).toString(16).padStart(2,'0')).join('').toUpperCase()}
function hexToHsv(hex:string){const n=parseInt(hex.slice(1),16),r=(n>>16&255)/255,g=(n>>8&255)/255,b=(n&255)/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d){if(max===r)h=60*((g-b)/d%6);else if(max===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4)}return{h:(h+360)%360,s:max?d/max:0,v:max}}
function hexAlpha(hex:string,alpha:number){const n=parseInt(hex.slice(1),16);return `rgba(${n>>16&255},${n>>8&255},${n&255},${alpha})`}
function layout(points:P[],w:number,h:number){
 const frame=points.map(p=>({x:p.x*w,y:p.y*h})),width=Math.hypot(frame[1].x-frame[0].x,frame[1].y-frame[0].y),height=Math.hypot(frame[2].x-frame[1].x,frame[2].y-frame[1].y)
 const horizontal=Math.max(4,Math.min(N/2-4,Math.round(N*width/(2*(width+height))))),vertical=(N-2*horizontal)/2,counts=[horizontal,vertical,horizontal,vertical]
 const anchors=[0,counts[0],counts[0]+counts[1],counts[0]+counts[1]+counts[2]]
 return{frame,counts,anchors,signature:counts.join(':')}
}
function build(points:P[],w:number,h:number):Particle[]{const {frame,counts}=layout(points,w,h),particles:Particle[]=[];counts.forEach((count,side)=>{const a=frame[side],b=frame[(side+1)%4];for(let i=0;i<count;i++){const f=i/count,x=a.x+(b.x-a.x)*f,y=a.y+(b.y-a.y)*f;particles.push({x,y,ox:x,oy:y})}});return particles}

function Slider({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(n:number)=>void}){
 const pct=(value-min)/(max-min)*100
 return <label className="parameter"><span><i>{label}</i><output>{value.toFixed(step<.1?2:1)}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} style={{'--p':pct+'%'} as React.CSSProperties} onChange={e=>onChange(+e.target.value)}/><small><b>{min}</b><b>{max}</b></small></label>
}

function ColorPicker({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){
 const [open,setOpen]=useState(false),hsv=hexToHsv(value),pure=hsvToHex(hsv.h,1,1)
 const setSv=(e:React.PointerEvent<HTMLDivElement>)=>{e.currentTarget.setPointerCapture?.(e.pointerId);const r=e.currentTarget.getBoundingClientRect(),s=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),v=1-Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));onChange(hsvToHex(hsv.h,s,v))}
 return <div className="color-picker"><button type="button" className="color-trigger" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><span className="swatch" style={{background:value}}/><span><b>{label}</b><small>{value}</small></span><i>{open?'−':'+'}</i></button>{open&&<div className="picker-pop"><div className="picker-head"><strong>Colour picker</strong><span>{value}</span></div><div className="picker-surface"><div className="picker-preview" style={{background:value}}/><div className="sv-plane" style={{'--hue':pure} as React.CSSProperties} onPointerDown={setSv} onPointerMove={e=>{if(e.buttons)setSv(e)}}><span style={{left:`${hsv.s*100}%`,top:`${(1-hsv.v)*100}%`,background:value}}/></div></div><div className="hue-row"><span className="hue-dot" style={{background:pure}}/><input className="hue" aria-label={`${label} hue`} type="range" min="0" max="360" value={hsv.h} style={{'--picked':pure} as React.CSSProperties} onChange={e=>onChange(hsvToHex(+e.target.value,hsv.s,hsv.v))}/></div></div>}</div>
}

function Canvas({points,setPoints,eyes,setEyes,pressure,stiffness,smoothing,contourLength,lineWidth,outlineColor,fillColor,eyeOutline,eyeFill,pupilColor,eyeLineWidth,pupilSize,paused,structure}:{points:P[];setPoints:React.Dispatch<React.SetStateAction<P[]>>;eyes:P[];setEyes:React.Dispatch<React.SetStateAction<P[]>>;pressure:number;stiffness:number;smoothing:number;contourLength:number;lineWidth:number;outlineColor:string;fillColor:string;eyeOutline:string;eyeFill:string;pupilColor:string;eyeLineWidth:number;pupilSize:number;paused:boolean;structure:number}){
 const ref=useRef<HTMLCanvasElement>(null), body=useRef<Particle[]>([]), size=useRef({w:0,h:0}), visualPoints=useRef(points.map(p=>({...p}))), mouse=useRef({x:0,y:0}), drag=useRef<{kind:'corner'|'eye';index:number}|null>(null), state=useRef({points,eyes,pressure,stiffness,smoothing,contourLength,lineWidth,outlineColor,fillColor,eyeOutline,eyeFill,pupilColor,eyeLineWidth,pupilSize,paused,structure})
 useEffect(()=>{state.current={points,eyes,pressure,stiffness,smoothing,contourLength,lineWidth,outlineColor,fillColor,eyeOutline,eyeFill,pupilColor,eyeLineWidth,pupilSize,paused,structure}},[points,eyes,pressure,stiffness,smoothing,contourLength,lineWidth,outlineColor,fillColor,eyeOutline,eyeFill,pupilColor,eyeLineWidth,pupilSize,paused,structure])
 useEffect(()=>{const c=ref.current!,ctx=c.getContext('2d')!;let frame=0
  const trackMouse=(event:PointerEvent)=>{const r=c.getBoundingClientRect();mouse.current={x:event.clientX-r.left,y:event.clientY-r.top}}
  window.addEventListener('pointermove',trackMouse)
  const resize=()=>{const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);c.width=r.width*d;c.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);if(!body.current.length||size.current.w!==r.width)body.current=build(visualPoints.current,r.width,r.height);size.current={w:r.width,h:r.height}}
  const ro=new ResizeObserver(()=>requestAnimationFrame(resize));ro.observe(c);resize()
  const loop=()=>{const {w,h}=size.current,s=state.current,b=body.current;visualPoints.current.forEach((p,i)=>{p.x+=(s.points[i].x-p.x)*.2;p.y+=(s.points[i].y-p.y)*.2});const geometry=layout(visualPoints.current,w,h);if(!s.paused&&b.length){
   const {frame,counts,anchors}=geometry
   const rest=counts.flatMap((count,side)=>{const a=frame[side],z=frame[(side+1)%4],length=Math.hypot(z.x-a.x,z.y-a.y)/count*s.contourLength;return Array(count).fill(length)})
   b.forEach(p=>{const vx=(p.x-p.ox)*.9,vy=(p.y-p.oy)*.9;p.ox=p.x;p.oy=p.y;p.x+=vx;p.y+=vy})
   const constraintPasses=4+Math.round(s.stiffness*.4),constraintStrength=Math.min(.46,.08+s.stiffness*.012)
   for(let q=0;q<constraintPasses;q++){
    for(let i=0;i<N;i++){const a=b[i],z=b[(i+1)%N],dx=z.x-a.x,dy=z.y-a.y,d=Math.hypot(dx,dy)||1,k=(d-rest[i])/d*constraintStrength;a.x+=dx*k;a.y+=dy*k;z.x-=dx*k;z.y-=dy*k}
    for(let i=0;i<N;i++){const p=b[i],a=b[(i+N-1)%N],z=b[(i+1)%N];p.x+=((a.x+z.x)/2-p.x)*s.smoothing*.03;p.y+=((a.y+z.y)/2-p.y)*s.smoothing*.03}
    frame.forEach((p,i)=>{const anchor=b[anchors[i]];anchor.x+=(p.x-anchor.x)*.86;anchor.y+=(p.y-anchor.y)*.86;anchor.ox=anchor.x;anchor.oy=anchor.y})
   }
   const mid=b.reduce((a,p)=>({x:a.x+p.x/N,y:a.y+p.y/N}),{x:0,y:0});b.forEach(p=>{const dx=p.x-mid.x,dy=p.y-mid.y,d=Math.hypot(dx,dy)||1;p.x+=dx/d*s.pressure*.025;p.y+=dy/d*s.pressure*.025})}
   ctx.clearRect(0,0,w,h);const glow=ctx.createRadialGradient(w/2,h/2,10,w/2,h/2,Math.max(w,h)*.45);glow.addColorStop(0,'rgba(124,255,191,.06)');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h)
   if(b.length){const last=b[N-1],first=b[0];ctx.beginPath();ctx.moveTo((last.x+first.x)/2,(last.y+first.y)/2);for(let i=0;i<N;i++){const p=b[i],z=b[(i+1)%N];ctx.quadraticCurveTo(p.x,p.y,(p.x+z.x)/2,(p.y+z.y)/2)}ctx.closePath();const fill=ctx.createLinearGradient(0,0,w,h);fill.addColorStop(0,hexAlpha(s.fillColor,.38));fill.addColorStop(1,hexAlpha(s.fillColor,.22));ctx.shadowColor=hexAlpha(s.outlineColor,.45);ctx.shadowBlur=28;ctx.fillStyle=fill;ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=s.outlineColor;ctx.lineWidth=s.lineWidth;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke()}
   s.eyes.forEach((eye,index)=>{const x=eye.x*w,y=eye.y*h,r=32,dx=mouse.current.x-x,dy=mouse.current.y-y,d=Math.hypot(dx,dy)||1,pupil=Math.min(s.pupilSize,r-s.eyeLineWidth-2),travel=Math.max(0,r-pupil-s.eyeLineWidth-3),px=x+dx/d*Math.min(travel,d*.16),py=y+dy/d*Math.min(travel,d*.16);ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=s.eyeFill;ctx.fill();ctx.lineWidth=s.eyeLineWidth;ctx.strokeStyle=s.eyeOutline;ctx.stroke();ctx.beginPath();ctx.arc(px,py,pupil,0,Math.PI*2);ctx.fillStyle=s.pupilColor;ctx.shadowColor=hexAlpha(s.pupilColor,.35);ctx.shadowBlur=8;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle=hexAlpha(s.eyeOutline,.65);ctx.font='7px DM Mono, monospace';ctx.fillText(`EYE 0${index+1}`,x-r,y+r+13);ctx.restore()})
   if(s.structure>.005){ctx.save();ctx.globalAlpha=s.structure;ctx.lineWidth=1;ctx.lineCap='butt';ctx.lineJoin='miter';ctx.setLineDash([2,7]);ctx.strokeStyle='rgba(167,255,213,.55)';ctx.beginPath();visualPoints.current.forEach((p,i)=>i?ctx.lineTo(p.x*w,p.y*h):ctx.moveTo(p.x*w,p.y*h));ctx.closePath();ctx.stroke();ctx.setLineDash([]);visualPoints.current.forEach((p,i)=>{const x=p.x*w,y=p.y*h;ctx.beginPath();ctx.arc(x,y,14,0,7);ctx.fillStyle='#081114';ctx.fill();ctx.strokeStyle='#527a69';ctx.lineWidth=1;ctx.stroke();ctx.beginPath();ctx.arc(x,y,5,0,7);ctx.fillStyle='#b5ffda';ctx.shadowColor='#7cffbf';ctx.shadowBlur=14;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#9ac7b4';ctx.font='9px monospace';ctx.fillText('0'+(i+1),x+20,y+3)});ctx.restore()}frame=requestAnimationFrame(loop)};loop();return()=>{window.removeEventListener('pointermove',trackMouse);ro.disconnect();cancelAnimationFrame(frame)}},[])
 const pos=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,w:r.width,h:r.height}}
 return <canvas ref={ref} aria-label="Interactief canvas; versleep de hoeken en beide ogen" onPointerDown={e=>{const m=pos(e),eye=eyes.findIndex(p=>Math.hypot(p.x*m.w-m.x,p.y*m.h-m.y)<38),corner=points.findIndex(p=>Math.hypot(p.x*m.w-m.x,p.y*m.h-m.y)<28);if(eye>=0)drag.current={kind:'eye',index:eye};else if(corner>=0)drag.current={kind:'corner',index:corner};if(drag.current)e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;const m=pos(e),x=Math.max(.07,Math.min(.93,m.x/m.w)),y=Math.max(.08,Math.min(.92,m.y/m.h));if(drag.current.kind==='eye'){const i=drag.current.index;setEyes(a=>a.map((p,j)=>j===i?{x,y}:p));return}const i=drag.current.index;setPoints(a=>{const next=a.map(p=>({...p}));next[i]={x,y};next[(i+1)%4][i%2===0?'y':'x']=i%2===0?y:x;next[(i+3)%4][i%2===0?'x':'y']=i%2===0?x:y;return next})}} onPointerUp={()=>drag.current=null}/>
}

export default function App(){const [points,setPoints]=useState(INITIAL),[eyes,setEyes]=useState<P[]>([{x:.42,y:.43},{x:.58,y:.43}]),[pressure,setPressure]=useState(3.4),[stiffness,setStiffness]=useState(6.2),[smoothing,setSmoothing]=useState(.72),[contourLength,setContourLength]=useState(1),[lineWidth,setLineWidth]=useState(2),[outlineColor,setOutlineColor]=useState('#A7FFD5'),[fillColor,setFillColor]=useState('#5AB7A8'),[eyeOutline,setEyeOutline]=useState('#A7FFD5'),[eyeFill,setEyeFill]=useState('#10282B'),[pupilColor,setPupilColor]=useState('#071014'),[eyeLineWidth,setEyeLineWidth]=useState(3),[pupilSize,setPupilSize]=useState(10),[paused,setPaused]=useState(false),[structure,setStructure]=useState(.7)
 const reset=()=>{setPoints(INITIAL.map(p=>({...p})));setEyes([{x:.42,y:.43},{x:.58,y:.43}]);setPressure(3.4);setStiffness(6.2);setSmoothing(.72);setContourLength(1);setLineWidth(2);setOutlineColor('#A7FFD5');setFillColor('#5AB7A8');setEyeOutline('#A7FFD5');setEyeFill('#10282B');setPupilColor('#071014');setEyeLineWidth(3);setPupilSize(10);setStructure(.7);setPaused(false)}
 return <main><header><div className="brand"><b>S/S</b>SOUL_SPAWN</div><div className="spec"><small>SPECIMEN</small>Creature 01</div><nav><button onClick={reset}>↺ RESET</button><button className="pause" onClick={()=>setPaused(v=>!v)}>{paused?'▶ RESUME':'Ⅱ PAUSE'}</button></nav></header><div className="workspace"><aside><div className="panel-title"><span>BODY PARAMETERS</span><small>+ EYES</small></div><Control n="01" title="Shape" tag="FORM"><Slider label="Length × perimeter" value={contourLength} min={.5} max={1.5} step={.01} onChange={setContourLength}/></Control><Control n="02" title="Physics" tag="FORCE"><Slider label="Pressure" value={pressure} min={-6} max={10} step={.1} onChange={setPressure}/><Slider label="Stiffness" value={stiffness} min={1} max={30} step={.5} onChange={setStiffness}/><Slider label="Smoothing" value={smoothing} min={0} max={1} step={.01} onChange={setSmoothing}/></Control><Control n="03" title="Body" tag="COLOR"><ColorPicker label="Outline" value={outlineColor} onChange={setOutlineColor}/><ColorPicker label="Body fill" value={fillColor} onChange={setFillColor}/><Slider label="Line width" value={lineWidth} min={.5} max={8} step={.5} onChange={setLineWidth}/><Slider label="Control points" value={structure} min={0} max={1} step={.01} onChange={setStructure}/></Control><Control n="04" title="Eyes" tag="DRAG TO MOVE"><ColorPicker label="Eye outline" value={eyeOutline} onChange={setEyeOutline}/><ColorPicker label="Eye fill" value={eyeFill} onChange={setEyeFill}/><ColorPicker label="Pupil" value={pupilColor} onChange={setPupilColor}/><Slider label="Eye outline width" value={eyeLineWidth} min={.5} max={10} step={.5} onChange={setEyeLineWidth}/><Slider label="Pupil size" value={pupilSize} min={2} max={24} step={1} onChange={setPupilSize}/></Control></aside><section className="stage"><div className="meta"><span>FORM / 001</span><span>RECTANGULAR FRAME</span></div><div className="canvas"><Canvas {...{points,setPoints,eyes,setEyes,pressure,stiffness,smoothing,contourLength,lineWidth,outlineColor,fillColor,eyeOutline,eyeFill,pupilColor,eyeLineWidth,pupilSize,paused,structure}}/><div className="hint"><b>⌁</b><span><strong>Drag form or eyes</strong><small>Pupils follow pointer</small></span></div></div><footer><span><i className={paused?'off':''}/> {paused?'SIMULATION PAUSED':'LIVE SIMULATION'}</span><span>EYES <b>02</b>　 STIFFNESS <b>{stiffness.toFixed(1)}</b></span></footer></section></div></main>}
function Control({n,title,tag,children}:{n:string;title:string;tag:string;children:React.ReactNode}){return <section className="control"><div className="label"><span>{n}</span><b>{title}</b><i>{tag}</i></div>{children}</section>}
